FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY .. .
RUN chmod +x ./mvnw
RUN ./mvnw clean package -DskipTests
RUN apt-get update && apt-get install -y \
  libglib2.0-0 \
  libnss3 \
  libnspr4 \
  libdbus-1-3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libatspi2.0-0 \
  libx11-6 \
  libxcomposite1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libxcb1 \
  libxkbcommon0 \
  libasound2t64 \
  wget \
  unzip \
  && apt-get clean
ENV PORT=8082
EXPOSE 8082
CMD ["java", "-jar", "marketplace-core/target/marketplace-core-0.0.1.jar"]
